# -*- coding: utf-8 -*-
"""Tugas EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1R8fnbVGXsmRwwxw2dY5wvCGgBSzhjD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-whitegrid')

data = {
    'jam_belajar': [1,2,3,4,5,6,7,8,2,3,4,5],
    'penggunaan_hp': [5,6,7,8,9,10,11,12,6,7,8,9],
    'akses_internet': [1,1,1,1,1,1,1,1,0,0,1,1],
    'nilai': [60,65,70,75,80,85,90,95,68,72,78,82]
}

df = pd.DataFrame(data)
df.head()

print("Ukuran:", df.shape)
print("\nKolom:", df.columns)
df.info()

df.describe()

df.isnull().sum()

df.hist(figsize=(10,6))
plt.suptitle('Distribusi Data Siswa')
plt.show()

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Korelasi Antar Variabel')
plt.show()

sns.scatterplot(x='jam_belajar', y='nilai', data=df)
plt.title('Jam Belajar vs Nilai')
plt.show()

sns.boxplot(data=df)
plt.title('Deteksi Outlier')
plt.show()

print("INSIGHT:")
print("- Semakin lama jam belajar, nilai cenderung meningkat")
print("- Penggunaan HP berlebihan bisa berpengaruh pada nilai")
print("- Akses internet membantu dalam pembelajaran digital")