# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4TXX-4kxQuZ8fxTMvh23S0Ovc0Tl06h
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-whitegrid')

df = pd.read_excel('Maths.csv')
df.head()

print("Ukuran Dataset:", df.shape)
print("\nKolom:")
print(df.columns)

df.info()

df.isnull().sum()

df = df.dropna()
df = df.drop_duplicates()

df_numeric = df.select_dtypes(include=['number'])
df_numeric.head()

df_numeric.describe()

df_numeric.hist(figsize=(12,8))
plt.suptitle('Distribusi Data')
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df_numeric.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(data=df_numeric)
plt.title('Deteksi Outlier')
plt.show()

target = df_numeric.columns[-1]
print("Target:", target)

for col in df_numeric.columns:
    if col != target:
        plt.figure(figsize=(5,3))
        sns.scatterplot(x=df_numeric[col], y=df_numeric[target])
        plt.title(f'{col} vs {target}')
        plt.show()